### ISSUE TITLE
Stripe Connect custom account for europe - IBAN

### ISSUE THREAD

**Issue by CYRZOG** [aidith/stripephp#1]
Hello, 

I changed to secret key and public key and while testing i got HTTP ERROR 500 once gettint to 
 page saveaccount.php or savecustomer.php !

any help  ?

Best regards,

**Comment by aidith** [comment]
Hi,

Have you add valid bank name and account holder details?
And also check does support in your country?
[https://stripe.com/global](https://stripe.com/global)

Thanks,

**Comment by CYRZOG** [comment]
Hello Aidith,

Thank you for your quick reply,

Yes it's supported in France, and Germany,
I am using a test mode : while testing i tried these IBAN : bank account

DE89370400440532013000

FR1420041010050500013M02606

and everytime it goes to saveaccount.php but i got a blank page !

Please check www.cyrinezoghlami.ovh for test.


Best regards,
Cyrine.
